
name: googledriveclone_flutter
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  fab_circular_menu: ^1.0.2
  floating_action_bubble: 1.0.9
  #file_picker: ^3.0.1
  path_provider: any
  flushbar: any
  get: ^4.1.4
  prompt_dialog: ^1.0.0
  font_awesome_flutter: ^9.0.0
  sk_alert_dialog: ^1.0.0
  #disk_space: ^0.1.0+2
  storage_capacity: ^0.0.7
  path: ^1.6.4
  path_provider_ex: ^1.0.1
  flutter_file_manager: ^0.1.1
  folder_file_saver: ^1.0.0+2
  dio: any

  #email_validator: ^1.0.0
  shared_preferences: any
  http: ^0.12.2
  permission_handler: ^8.0.0+2
  ext_storage: ^1.0.3
  cupertino_icons: ^0.1.3
  #----------------------
  provider: ^4.3.2+4
  rxdart: ^0.22.6
  #path_provider: ^1.1.0
  flutter_statusbarcolor: ^0.2.0
  flutter_document_picker: ^4.0.1
  toast: ^0.1.5
  share: ^0.6.1+1
  open_file: ^2.1.1
  url_launcher: ^5.2.7
  page_transition: ^1.1.0
  simple_permissions:
    git:
      url: https://github.com/tq-systems/simple_permissions.git
  package_info: ^0.4.0+12
  esys_flutter_share: ^1.0.2
  #package renamer
  change_app_package_name: ^0.1.3
  #pic chart
  flutter_svg: any
  fl_chart: ^0.36.2
  flutter_launcher_icons: ^0.8.0
  flutter_pdfview: ^1.0.4
  flutter_swiper: ^1.1.6
  flutter_local_notifications: ^1.0.0
  toggle_switch: ^1.2.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"




dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/ic_launcher.png
    - assets/safe.png
    - assets/google-docs.png
    - assets/google-sheets.png
    - assets/pdf.png
    - assets/photo.png
    - assets/photographic-film.png
    - assets/unknown_file_type2.png # source: https://www.iconfinder.com/icons/285688/empty_file_icon
    - assets/details.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
